#  Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import pandas as pd

C:\Users\User\AppData\Local\Temp\ipykernel_15372\3903510217.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
import numpy as np

In [3]:
# warning
import warnings
warnings.filterwarnings('ignore')

In [4]:
#load given dataset
data = pd.read_csv("C:\\Users\\User\\Desktop\\fproject\\dataset\\liver_patient.csv")

In [5]:
data.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [6]:
#Checking datatype and information about dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1165 entries, 0 to 1164
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         1165 non-null   int64  
 1   Gender                      1165 non-null   object 
 2   Total_Bilirubin             1165 non-null   float64
 3   Direct_Bilirubin            1165 non-null   float64
 4   Alkaline_Phosphotase        1165 non-null   int64  
 5   Alamine_Aminotransferase    1165 non-null   int64  
 6   Aspartate_Aminotransferase  1165 non-null   int64  
 7   Total_Protiens              1165 non-null   float64
 8   Albumin                     1165 non-null   float64
 9   Albumin_and_Globulin_Ratio  1157 non-null   float64
 10  Dataset                     1165 non-null   int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 100.2+ KB


In [7]:
#To describe the dataframe
data.describe()

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
count  1165.000000      1165.000000       1165.000000           1165.000000   
mean     44.732189         3.301030          1.487296            290.575966   
std      16.182816         6.209119          2.808200            242.938261   
min       4.000000         0.400000          0.100000             63.000000   
25%      33.000000         0.800000          0.200000            175.000000   
50%      45.000000         1.000000          0.300000            208.000000   
75%      58.000000         2.600000          1.300000            298.000000   
max      90.000000        75.000000         19.700000           2110.000000   

       Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
count               1165.000000                 1165.000000     1165.000000   
mean                  80.650644                  109.804292        6.480258   
std                  182.629624                  288.896796        1.083723   
min                   10.000000                   10.000000        2.700000   
25%                   24.000000                   25.000000        5.800000   
50%                   35.000000                   42.000000        6.600000   
75%                   60.000000                   87.000000        7.200000   
max                 2000.000000                 4929.000000        9.600000   

           Albumin  Albumin_and_Globulin_Ratio      Dataset  
count  1165.000000                 1157.000000  1165.000000  
mean      3.140601                    0.947018     1.286695  
std       0.794715                    0.319724     0.452412  
min       0.900000                    0.300000     1.000000  
25%       2.600000                    0.700000     1.000000  
50%       3.100000                    0.930000     1.000000  
75%       3.800000                    1.100000     2.000000  
max       5.500000                    2.800000     2.000000

In [8]:
#duplicate data
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1160     True
1161     True
1162     True
1163     True
1164     True
Length: 1165, dtype: bool

In [9]:
# sum of duplicated 
data.duplicated().sum()

587

In [10]:
data = data.drop_duplicates()

In [11]:
data.duplicated().sum()

0

In [12]:
#sum of null values
data.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [13]:
#drop null values
df=data.dropna()

In [14]:
df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [15]:
#changing feature name
df = df.rename({'Dataset': 'Result'}, axis=1)

In [16]:
df.head(10)

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   
5   46    Male              1.8               0.7                   208   
6   26  Female              0.9               0.2                   154   
7   29  Female              0.9               0.3                   202   
8   17    Male              0.9               0.3                   202   
9   55    Male              0.7               0.2                   290   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   
5                        19                          14             7.6   
6                        16                          12             7.0   
7                        14                          11             6.7   
8                        22                          19             7.4   
9                        53                          58             6.8   

   Albumin  Albumin_and_Globulin_Ratio  Result  
0      3.3                        0.90       1  
1      3.2                        0.74       1  
2      3.3                        0.89       1  
3      3.4                        1.00       1  
4      2.4                        0.40       1  
5      4.4                        1.30       1  
6      3.5                        1.00       1  
7      3.6                        1.10       1  
8      4.1                        1.20       2  
9      3.4                        1.00       1

In [17]:
df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Result'],
      dtype='object')

In [18]:
df.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [19]:
df.Age.unique()

array([65, 62, 58, 72, 46, 26, 29, 17, 55, 57, 64, 74, 61, 25, 38, 33, 40,
       51, 63, 34, 20, 84, 52, 30, 48, 47, 45, 42, 50, 85, 35, 21, 32, 31,
       54, 37, 66, 60, 19, 75, 68, 70, 49, 14, 13, 18, 39, 27, 36, 24, 28,
       53, 15, 56, 44, 41,  7, 22,  8,  6,  4, 43, 23, 12, 69, 16, 78, 11,
       73, 67, 10, 90], dtype=int64)

In [20]:
df['Total_Bilirubin'].unique()

array([ 0.7, 10.9,  7.3,  1. ,  3.9,  1.8,  0.9,  0.6,  2.7,  0.8,  1.1,
        1.6,  2.2,  2.9,  6.8,  1.9,  4.1,  6.2,  4. ,  2.6,  1.3, 14.2,
        1.4,  2.4, 18.4,  3.1,  8.9,  2.8,  2. ,  5.7,  8.6,  5.8,  5.2,
        3.8,  6.6,  0.5,  5.3,  3.2,  1.2, 12.7, 15.9, 18. , 23. , 22.7,
        1.7,  3. , 11.3,  4.7,  4.2,  3.5,  5.9,  8.7, 11. , 11.5,  4.5,
       75. , 22.8, 14.1, 14.8, 10.6,  8. ,  1.5,  2.1,  6.3,  2.3, 27.2,
        2.5,  3.6, 30.5, 16.4, 14.5, 18.5, 23.2,  3.7,  3.3,  7.1,  6.7,
       22.6,  7.5,  5. ,  4.9,  8.2,  0.4,  7.4, 23.3,  7.9,  3.4, 19.8,
       32.6, 17.7, 20. , 26.3,  4.4,  9.4, 30.8, 19.6, 15.8,  5.5, 20.2,
       27.7, 11.1, 10.2, 42.8, 15.2, 16.6, 17.3, 22.5, 16.7,  7.7, 15.6,
       12.1, 25. , 15. ])

In [21]:
df[ 'Direct_Bilirubin'].unique()

array([ 0.1,  5.5,  4.1,  0.4,  2. ,  0.7,  0.2,  0.3,  1.3,  0.8,  0.5,
        1. ,  3. ,  1.9,  1.2,  7.8,  0.6,  1.1,  3.2,  1.8,  8.8,  1.6,
        4.5,  2.8,  4. ,  2.7,  2.4,  1.5,  2.3,  3.6,  6.2,  7. ,  8.2,
       11.3, 10.2,  2.5,  1.4,  1.7,  5.6,  2.2,  2.1,  4.9,  5. ,  0.9,
       12.6,  7.6,  9. ,  4.6, 11.8, 14.2,  8.9,  6.4,  9.5,  3.3, 11.4,
        4.3,  3.7,  2.6,  3.9,  5.1, 12.8, 10.4, 17.1, 14.1,  8.5, 10. ,
       12.1,  2.9,  5.2, 18.3,  7.2, 11.7, 10.8,  6.1,  4.2, 19.7,  7.7,
        8.4,  6. , 13.7])

In [22]:
df['Alkaline_Phosphotase'].unique()

array([ 187,  699,  490,  182,  195,  208,  154,  202,  290,  210,  260,
        305,  214,  145,  183,  342,  165,  293,  610,  482,  542,  231,
        194,  289,  240,  128,  188,  190,  156,  410,  374,  263,  275,
        168,  160,  630,  415,  150,  230,  176,  206,  170,  161,  253,
        198,  272,  175,  367,  158,  259,  470,  215,  239,  186,  205,
        171,  162,  518, 1620,  146,  670,  915,   75,  148,  258,  237,
        269,  320,  298,  538,  238,  308,  204,  282,  265,  312,  243,
        224,  225,  486,  257,  179,  661, 1580, 1630,  280,  300,  178,
        177,  201,  802,  248, 1896,  512,  199, 1110,  310,  380,  159,
        332,  189,  392,  286,  180,  218,  462,  196,  750, 1050,  599,
        292,  962,  950,  200, 1020,  562,  386,  250,  191,  614,  314,
        209, 1124,  664,  142,  169, 1420,  135,  163,  285,  350,  220,
        219,  401,  100,  116,  125,  147,  192,  400,  120,  173,  157,
       2110,  360,  316,  498,  480,  680,  152,  8

In [23]:
df['Alamine_Aminotransferase'].unique()

array([  16,   64,   60,   14,   27,   19,   22,   53,   51,   31,   91,
        168,   15,  232,   17,  116,   52,  875, 1680,   20,   13,   45,
         35,   59,  102,   18,   38,  123,   33,   42,   25,  407,   48,
         36, 1630,   39,   21,   80,   86,   26,   24,   37,   40,   62,
         55,  166,  189,   95,   12,  194,   58,   28,  119,  412,  404,
        220,  126,  190,   97,  308,   32,   29,   11,   63,  181,   88,
         74, 2000, 1350, 1250,  482,  322,  133,   46,   61,   57,   50,
         34,   72,   84,   30,   70,  140,   99,   43,  378,  112,   71,
         23,   79,  114,  118,  107,  790,  950,   82,   41,   56,  149,
        230,   69,   90,   89,  148,   65,  205,   96,  152,  390,   10,
        120,   78,  178,  179,   47,  160,   54,  198,   85,   44,  349,
        110,  115,   94,  142,  137,  155,  157,  141,  284,  440,   93,
         76,   49,  425,  159,  622,  779,  132,  154,  196,   68,  509,
         67,  139,  382,   75,  321,  233,  173,  2

In [24]:
df['Total_Protiens'].unique()

array([6.8, 7.5, 7. , 7.3, 7.6, 6.7, 7.4, 5.9, 6. , 8.1, 5.8, 5.5, 6.4,
       4.3, 5. , 7.2, 3.9, 5.2, 4.9, 5.6, 6.9, 6.2, 5.1, 6.1, 6.5, 5.7,
       6.6, 6.3, 8. , 4.4, 5.3, 4.6, 4.7, 5.4, 7.1, 4. , 3.7, 2.7, 3. ,
       3.8, 7.8, 4.5, 4.1, 4.8, 7.9, 8.3, 7.7, 8.2, 8.5, 2.8, 9.5, 9.6,
       8.6, 8.4, 8.9, 8.7, 3.6, 9.2])

In [25]:
df['Albumin'].unique()

array([3.3, 3.2, 3.4, 2.4, 4.4, 3.5, 3.6, 4.1, 2.7, 3. , 2.3, 3.1, 2.6,
       1.6, 3.9, 4. , 1.9, 1.5, 2.9, 2. , 2.2, 2.8, 1.8, 2.5, 2.1, 3.7,
       3.8, 4.3, 1.7, 4.2, 4.5, 0.9, 1.4, 4.7, 5.5, 4.9, 4.6, 5. , 4.8,
       1. ])

In [26]:
df['Albumin_and_Globulin_Ratio'].unique()

array([0.9 , 0.74, 0.89, 1.  , 0.4 , 1.3 , 1.1 , 1.2 , 0.8 , 0.6 , 0.87,
       0.7 , 0.92, 0.55, 0.5 , 1.85, 0.95, 1.4 , 1.18, 0.61, 1.34, 1.39,
       1.6 , 1.58, 1.25, 0.78, 0.76, 1.55, 0.71, 0.62, 0.67, 0.75, 1.16,
       1.5 , 1.66, 0.96, 1.38, 0.52, 0.47, 0.93, 0.48, 0.58, 0.69, 1.27,
       1.12, 1.06, 0.53, 1.03, 0.68, 1.9 , 1.7 , 1.8 , 0.3 , 0.97, 0.35,
       1.51, 0.64, 0.45, 1.36, 0.88, 1.09, 1.11, 1.72, 2.8 , 0.46, 0.39,
       1.02, 2.5 , 0.37])

In [27]:
df["Result"].unique()

array([1, 2], dtype=int64)

In [28]:
df.columns

Index(['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio', 'Result'],
      dtype='object')

In [29]:
pd.Categorical(df['Age']).describe()

counts     freqs
categories                  
4                2  0.003484
6                1  0.001742
7                2  0.003484
8                1  0.001742
10               1  0.001742
...            ...       ...
75              14  0.024390
78               1  0.001742
84               1  0.001742
85               1  0.001742
90               1  0.001742

[72 rows x 2 columns]

In [30]:
pd.Categorical(df['Gender']).describe()

counts     freqs
categories                  
Female         140  0.243902
Male           434  0.756098

In [31]:
pd.Categorical(df['Result']).describe()

counts     freqs
categories                  
1              407  0.709059
2              167  0.290941

In [32]:
pd.Categorical(df['Total_Bilirubin']).describe()

counts     freqs
categories                  
0.4              1  0.001742
0.5              5  0.008711
0.6             44  0.076655
0.7             78  0.135889
0.8             91  0.158537
...            ...       ...
30.5             2  0.003484
30.8             1  0.001742
32.6             1  0.001742
42.8             1  0.001742
75.0             1  0.001742

[113 rows x 2 columns]

In [33]:
pd.Categorical(df['Direct_Bilirubin']).describe()

counts     freqs
categories                  
0.1             61  0.106272
0.2            194  0.337979
0.3             50  0.087108
0.4             20  0.034843
0.5             19  0.033101
...            ...       ...
14.1             1  0.001742
14.2             1  0.001742
17.1             1  0.001742
18.3             1  0.001742
19.7             1  0.001742

[80 rows x 2 columns]

In [34]:
pd.Categorical(df['Alkaline_Phosphotase']).describe()

counts     freqs
categories                  
63               1  0.001742
75               1  0.001742
90               1  0.001742
92               2  0.003484
97               1  0.001742
...            ...       ...
1620             1  0.001742
1630             1  0.001742
1750             1  0.001742
1896             1  0.001742
2110             1  0.001742

[262 rows x 2 columns]

In [35]:
pd.Categorical(df['Alamine_Aminotransferase']).describe()

counts     freqs
categories                  
10               4  0.006969
11               2  0.003484
12               9  0.015679
13               4  0.006969
14               8  0.013937
...            ...       ...
1250             2  0.003484
1350             1  0.001742
1630             1  0.001742
1680             1  0.001742
2000             1  0.001742

[152 rows x 2 columns]

In [36]:
pd.Categorical(df['Total_Protiens']).describe()

counts     freqs
categories                  
2.7              1  0.001742
2.8              1  0.001742
3.0              1  0.001742
3.6              3  0.005226
3.7              1  0.001742
3.8              3  0.005226
3.9              2  0.003484
4.0              2  0.003484
4.1              2  0.003484
4.3              3  0.005226
4.4              4  0.006969
4.5              4  0.006969
4.6              4  0.006969
4.7              2  0.003484
4.8              3  0.005226
4.9              6  0.010453
5.0              9  0.015679
5.1             10  0.017422
5.2             11  0.019164
5.3             11  0.019164
5.4             14  0.024390
5.5             16  0.027875
5.6             16  0.027875
5.7             11  0.019164
5.8             13  0.022648
5.9             14  0.024390
6.0             29  0.050523
6.1             18  0.031359
6.2             24  0.041812
6.3             14  0.024390
6.4             18  0.031359
6.5             14  0.024390
6.6             15  0.026132
6.7             16  0.027875
6.8             28  0.048780
6.9             25  0.043554
7.0             32  0.055749
7.1             22  0.038328
7.2             20  0.034843
7.3             18  0.031359
7.4             11  0.019164
7.5             15  0.026132
7.6              9  0.015679
7.7              3  0.005226
7.8              9  0.015679
7.9             14  0.024390
8.0             20  0.034843
8.1              6  0.010453
8.2              8  0.013937
8.3              4  0.006969
8.4              3  0.005226
8.5              3  0.005226
8.6              3  0.005226
8.7              1  0.001742
8.9              1  0.001742
9.2              2  0.003484
9.5              1  0.001742
9.6              1  0.001742

In [37]:
pd.Categorical(df['Albumin']).describe()

counts     freqs
categories                  
0.9              2  0.003484
1.0              1  0.001742
1.4              4  0.006969
1.5              3  0.005226
1.6              8  0.013937
1.7              3  0.005226
1.8             12  0.020906
1.9              7  0.012195
2.0             19  0.033101
2.1             14  0.024390
2.2             11  0.019164
2.3             12  0.020906
2.4             16  0.027875
2.5             24  0.041812
2.6             20  0.034843
2.7             22  0.038328
2.8             19  0.033101
2.9             30  0.052265
3.0             44  0.076655
3.1             26  0.045296
3.2             26  0.045296
3.3             23  0.040070
3.4             21  0.036585
3.5             23  0.040070
3.6             17  0.029617
3.7             20  0.034843
3.8             16  0.027875
3.9             24  0.041812
4.0             37  0.064460
4.1             16  0.027875
4.2             13  0.022648
4.3             12  0.020906
4.4              8  0.013937
4.5              6  0.010453
4.6              4  0.006969
4.7              3  0.005226
4.8              1  0.001742
4.9              4  0.006969
5.0              1  0.001742
5.5              2  0.003484

In [38]:
pd.Categorical(df['Albumin_and_Globulin_Ratio']).describe()

counts     freqs
categories                  
0.30             4  0.006969
0.35             1  0.001742
0.37             1  0.001742
0.39             1  0.001742
0.40            14  0.024390
...            ...       ...
1.80             3  0.005226
1.85             2  0.003484
1.90             1  0.001742
2.50             2  0.003484
2.80             1  0.001742

[69 rows x 2 columns]

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
var_mod = {'Gender'}
le=LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [41]:
df.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Result  
0      3.3                        0.90       1  
1      3.2                        0.74       1  
2      3.3                        0.89       1  
3      3.4                        1.00       1  
4      2.4                        0.40       1

In [42]:
df.corr()

Age    Gender  Total_Bilirubin  \
Age                         1.000000  0.055803         0.004742   
Gender                      0.055803  1.000000         0.088014   
Total_Bilirubin             0.004742  0.088014         1.000000   
Direct_Bilirubin           -0.000544  0.100194         0.874185   
Alkaline_Phosphotase        0.074911 -0.023596         0.206120   
Alamine_Aminotransferase   -0.087815  0.082962         0.217430   
Aspartate_Aminotransferase -0.021210  0.080687         0.239014   
Total_Protiens             -0.206173 -0.093133        -0.004935   
Albumin                    -0.272324 -0.092707        -0.221246   
Albumin_and_Globulin_Ratio -0.213303 -0.002848        -0.207496   
Result                     -0.118904 -0.073852        -0.224693   

                            Direct_Bilirubin  Alkaline_Phosphotase  \
Age                                -0.000544              0.074911   
Gender                              0.100194             -0.023596   
Total_Bilirubin                     0.874185              0.206120   
Direct_Bilirubin                    1.000000              0.234568   
Alkaline_Phosphotase                0.234568              1.000000   
Alamine_Aminotransferase            0.237494              0.126782   
Aspartate_Aminotransferase          0.259078              0.167270   
Total_Protiens                      0.003976             -0.025214   
Albumin                            -0.226912             -0.162929   
Albumin_and_Globulin_Ratio         -0.200823             -0.234255   
Result                             -0.251431             -0.187274   

                            Alamine_Aminotransferase  \
Age                                        -0.087815   
Gender                                      0.082962   
Total_Bilirubin                             0.217430   
Direct_Bilirubin                            0.237494   
Alkaline_Phosphotase                        0.126782   
Alamine_Aminotransferase                    1.000000   
Aspartate_Aminotransferase                  0.791894   
Total_Protiens                             -0.031740   
Albumin                                    -0.025074   
Albumin_and_Globulin_Ratio                 -0.006168   
Result                                     -0.161732   

                            Aspartate_Aminotransferase  Total_Protiens  \
Age                                          -0.021210       -0.206173   
Gender                                        0.080687       -0.093133   
Total_Bilirubin                               0.239014       -0.004935   
Direct_Bilirubin                              0.259078        0.003976   
Alkaline_Phosphotase                          0.167270       -0.025214   
Alamine_Aminotransferase                      0.791894       -0.031740   
Aspartate_Aminotransferase                    1.000000       -0.019059   
Total_Protiens                               -0.019059        1.000000   
Albumin                                      -0.082746        0.785160   
Albumin_and_Globulin_Ratio                   -0.071724        0.238659   
Result                                       -0.151329        0.023849   

                             Albumin  Albumin_and_Globulin_Ratio    Result  
Age                        -0.272324                   -0.213303 -0.118904  
Gender                     -0.092707                   -0.002848 -0.073852  
Total_Bilirubin            -0.221246                   -0.207496 -0.224693  
Direct_Bilirubin           -0.226912                   -0.200823 -0.251431  
Alkaline_Phosphotase       -0.162929                   -0.234255 -0.187274  
Alamine_Aminotransferase   -0.025074                   -0.006168 -0.161732  
Aspartate_Aminotransferase -0.082746                   -0.071724 -0.151329  
Total_Protiens              0.785160                    0.238659  0.023849  
Albumin                     1.000000                    0.688588  0.157171  
Albumin_and_Globulin_Ratio  0.688588                   

In [43]:
df.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Result  
0      3.3                        0.90       1  
1      3.2                        0.74       1  
2      3.3                        0.89       1  
3      3.4                        1.00       1  
4      2.4                        0.40       1